<?php
/* 
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: cittadhammo
 * Date: Tue, 06 Apr 2021 16:44:45 +0000
 */

$conf['title'] = 'Fractal Dhamma';
$conf['template'] = 'fractal10';
$conf['maxtoclevel'] = '0';
$conf['maxseclevel'] = '0';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['useslash'] = 1;
$conf['proxy']['user'] = 'cittadhammo';
$conf['proxy']['pass'] = '<b>bW9uY2hhdHJibmdyMTYyMQ==';
