<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: cittadhammo
 * Date: Sun, 25 Jul 2021 20:45:11 +0000
 */

$conf['title'] = 'Fractal Dhamma';
$conf['template'] = 'fractal10';
$conf['maxtoclevel'] = '0';
$conf['maxseclevel'] = '0';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['useslash'] = 1;
$conf['defer_js'] = 0;
$conf['proxy']['user'] = 'cittadhammo';
$conf['proxy']['pass'] = '<b>bW9uY2hhdHJibmdyMTYyMQ==';
$conf['plugin']['indexmenu']['hide_headpage'] = 0;
$conf['plugin']['indexmenu']['page_index'] = 'sitemap';
$conf['tpl']['fractal10']['prsnl10_headernav'] = 0;
$conf['tpl']['fractal10']['prsnl10_copyright'] = 0;
$conf['tpl']['fractal10']['prsnl10_copyright_default'] = 0;
