<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: cittadhammo
 * Date: Thu, 01 Apr 2021 03:35:07 -0400
 */

$conf['title'] = 'Fractal Dhamma';
$conf['template'] = 'fractal10';
$conf['maxtoclevel'] = '0';
$conf['maxseclevel'] = '0';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
