# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 31 Mar 2021 08:59:36 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

cittadhammo:$2y$10$J8vhH3rMSVpFpcGfY6IHNuBPuvhweSCsKyjMhFC8RE5.BzLV.qL0O:lancelot moreau:lanmoreau@hotmail.com:admin,user
